### PR TITLE
Add support for custom cooldowns

### LINKED ISSUE #57: Custom Cooldowns
### Summary
Allow for dynamic cooldowns that vary based on a given predicate

### Ideal implementation
```py
def predicate(ctx: Context) -> Cooldown:
    if ctx.author_id == 123456789:
        return Cooldown(60, 1, UserBucket)

@custom_cooldown(predicate)
@command()
async def test(ctx: Context) -> None: ...
```

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

### PR DESCRIPTION
**Pull request by norinorin**
### Summary
This PR implements custom cooldown support. Yet, I haven't updated the docs/docstrings as I'm not so sure how to document overloads nor familiar with sphinx.

### Checklist
- [x] I have run `nox` and all the pipelines have passed.
- [ ] I have made unittests according to the code I have added/modified/deleted.

### Related issues
Close #57

### CODE REVIEW

**Comment by YodaPY** [comment]
Why not make a decorator for custom commands? That way you don't have to validate the arguments.

**Comment by norinorin** [comment]
> Why not make a decorator for custom commands? That way you don't have to validate the arguments.

If Thomm.o is okay with that, sure, I can make it separate.

**Comment by tandemdude** [comment]
I think a separate decorator here could possibly work better - allows for clearer documentation too potentially.

**Comment by norinorin** [comment]
Are you guys okay with the naming?

**Comment by YodaPY** [comment]
dynamic_cooldown seems fine yeah

**Comment by norinorin** [comment]
New issues due to function overloading should be ignored on Codacy for the checks to pass. Also, CI/test would pass if the base branch did.

**Pull request merged**
