### PR TITLE
Application Command Localization support

### PR DESCRIPTION
**Pull request by MakufonSkifto**
### Summary
This PR implements [Application Command Localization](https://github.com/hikari-py/hikari/pull/1141).

### Checklist
- [x] I have run `nox` and all the pipelines have passed.

### CODE REVIEW

**Comment by tandemdude** [comment]
@MakufonSkifto can you rebase this pr please

**Comment by MakufonSkifto** [comment]
> @MakufonSkifto can you rebase this pr please

done

**Comment by tandemdude** [comment]
> > @MakufonSkifto can you rebase this pr please
> 
> done

Doesn't look very rebased to me

```
git rebase --hard f80b2709119d5afa7ce28c6350a7ac8d2601d74f
git remote add upstream https://github.com/tandemdude/hikari-lightbulb.git
git fetch upstream development
git rebase FETCH_HEAD
git push -f
```

**Comment by PerchunPak** [comment]
If there are no plans to continue this PR, could I take it? (I know that only thing, that left - run `black`)

**Comment by PerchunPak** [comment]
I think 10 days is enough. See #283.

**Pull request closed without merging**
