### PR TITLE
Add dark mode for docs

### LINKED ISSUE #120: Implement dark mode for docs
### Summary
Add an extension that allows for the standard RTD theme to have a togglable dark mode.

### Problem
Docs were only in light mode, when a lot of people would like to have a dark mode available.

### Ideal implementation
I'm gonna make a PR for this in a bit.

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

### PR DESCRIPTION
**Pull request by parafoxia**
### Summary
See #120.

### Checklist
- [x] I have run `nox` and all the pipelines have passed.
- [ ] I have made unittests according to the code I have added/modified/deleted.

### Related issues
Close #120.

### CODE REVIEW

**Comment by thomm-o** [comment]
This plugin seems to break list formatting so is not mergeable in its current state.

Before:
Screenshot 2021-09-27 at 17 14 04
After:
Screenshot 2021-09-27 at 17 13 20

**Comment by parafoxia** [comment]
Huh, I'm not getting the same issue on my end.
image

**Comment by thomm-o** [comment]
I'll get rtd to build it and see what they come out with

**Comment by thomm-o** [comment]
Seems to work on readthedocs - not sure why it isn't working on my laptop...
So I'm happy to merge this

**Comment by parafoxia** [comment]
Sphinx being sphinx I spose haha.

**Pull request merged**
